### PR TITLE
catkinize the packages to work on hydro

### PR DESCRIPTION
**Pull request by garaemon**

### CODE REVIEW

**Comment by garaemon** [comment]
This repository is not maintained?

**Comment by sosentos** [comment]
Sorry about the slow reply.  I have been doing a lot of end of the year reporting.  I will try to test this on my machine and then pull it in by Friday.

**Comment by sosentos** [comment]
Ok I've tested this and it makes just great in hydro.  Thanks!

Just a warning, the launch file in pr2_teleop and some other things are broken if you try to run them.  I will make a list of problems that I see at a high level so that they are documented.

But this can be handled through a larger set of pull requests so I will pull this in now.

**Comment by garaemon** [comment]
we are using safe_teleop_base on hydro, PR2 and it works well!

**Pull request merged**
