### PR TITLE
add 'ROS Orphaned Package Maintainers' as maintainer

### PR DESCRIPTION
**Pull request by furushchev**
@pitzer We are willing to release this repository on behalf of unmaintaned package maintaner groups, so could you give @k-okada write access? Thank you in advance!

### CODE REVIEW

**Comment by k-okada** [comment]
@dejanpan thanks!!!!

**Comment by dejanpan** [comment]
I added write access for @k-okada. Is this enough?

thank you so much.

**Comment by k-okada** [comment]
@dirk-thomas I'm planning to release this package, can you add shared_autonomy_manipulation-release repository to https://github.com/ros-gbp ?
if not @dejanpan can you create empty shared_autonomy_manipulation-release repository to this organization,
if not can I release from my repository?

**Comment by furushchev** [comment]
@dejanpan Thanks too from me!

**Comment by dejanpan** [comment]
I can also create a release repo. LMK whatever is best for you.

**Comment by k-okada** [comment]
@dejanpan, @furushchev  thank you for your help, finally we can release into indigo -> https://github.com/ros-gbp/shared_autonomy_manipulation-release

**Comment by dejanpan** [comment]
thx a lot guys, really appreciated.

**Pull request merged**
